### ISSUE TITLE
Products Fail to Update Automatically

### ISSUE THREAD

**Issue by airbusman5514** [Unidata/awips2#202]
Whenever I'm tracking some severe weather event, the products loaded never automatically refresh. I have to choose Time Match Basis a few times until the radar finally loads. Any ideas on how to fix this? A re-install didn't work.

**Comment by mjames-upc** [comment]
In CAVE > Preferences > Thin Client > Connections change from **Automatic Push** to **Timed Poll** and set the data update interval to 1 minute.   In the next release 17.1.1-4 this will be the default setting. 

I recently discovered that with the new distributed EDEX environment in the cloud, data push notifications originate from the decoder instance rather than the request/database instance.  For now this client workaround is the best solution.
