### ISSUE TITLE
wrong version shown in 18.1.1-6

### ISSUE THREAD

**Issue by suschizu** [Unidata/awips2#279]
I noticed that the version number from the latest download is still 18.1.1-4 although the info claims that it should be 18.1.1-6: 

![Screenshot 2019-03-25 at 12 31 53](https://user-images.githubusercontent.com/16004333/54916848-ba8b6980-4efa-11e9-9c41-dc7bd33f5fb7.png)
![Screenshot 2019-03-25 at 12 31 31](https://user-images.githubusercontent.com/16004333/54916854-bcedc380-4efa-11e9-9299-2fd803531b75.png)

**Comment by haircut** [comment]
Yes, please update the `CFBundleShortVersionString` for Cave's `Info.plist`!

This causes issues with our version detection and complicates application updates for managed environments, such as higher education. We're currently unable to target machines _not_ running `18.1.1-6` because even if they _are_ running the current version, the app presents itself otherwise.

I'd also suggest, humbly, moving to a [SemVer](https://semver.org) based versioning scheme instead of the "dash-tag" currently used. `18.1.1.6` would convey the same information and be more easily compatible with version detection mechanisms.

For an even more specific example, please see the necessity of version number manipulation in my [Cave recipe](https://github.com/autopkg/haircut-recipes/blob/master/Unidata/CAVE.pkg.recipe#L29-L39) for [autopkg](https://github.com/autopkg/autopkg).

**Comment by mjames-upc** [comment]
@haircut thank you for the feedback, I was just about to release a new macOS client and have updated the version number to be correct, and have adopted SemVer formatting.  You can download the new DMG at https://www.unidata.ucar.edu/downloads/awips2/awips-cave-18.1.1.7.dmg
